deployment:
  tasks:
    - cd /home4/balumaba/repositories/baluma # Navigate to the repository directory
    - npm install # Install dependencies
    - npm run build # Build the application
    - export DEPLOY_DIR=/home4/balumaba/public_html # Set deployment directory
    - /bin/cp -R dist/* $DEPLOY_DIR # Copy built files to the deployment directory
    - /bin/cp .env $DEPLOY_DIR/.env # Optionally copy environment variables
