---
deployment:
  tasks:
    - echo "Starting deployment..."
    - cd /home2/outretr2/repositories/outreach
    - export DEPLOY_DIR=/home2/outretr2/public_html
    - /bin/cp -R dist/* $DEPLOY_DIR
    - echo "Deployment completed."
