deployment:
  tasks:
    - echo "Starting deployment..."
    - cd /home2/outretr2/repositories/outretreat && echo "Navigated to repository directory"
    - npm install && echo "Dependencies installed"
    - npm run build && echo "Build completed"
    - export DEPLOY_DIR=/home2/outretr2/public_html && echo "Deployment directory set"
    - /bin/cp -R dist/* $DEPLOY_DIR && echo "Files copied to public_html"
    - /bin/cp .env $DEPLOY_DIR/.env && echo ".env copied"
